<?php
if(isset($_REQUEST['d_id'])){
    $delete_id=$_REQUEST['d_id'];
}else{
}
$exist=$wpdb->delete('employee',array(
    'employee_id'=>$delete_id
));
if($exist==true){
    $rc=0;
    $msg="删除成功";
}else{
    $rc=4;
    $msg="删除失败";
}
$rv->exist=$exist;
$rv->rc=$rc;
$rv->msg=$msg;
exit(json_encode($rv));
?>